# Generated by Django 3.2.12 on 2023-10-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20231007_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liking_users', to='network.Post'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
